name: "Submit a bug/crash/error."
description: "Something doesn't work as expected. Please specify the mod name and provide a crash report if possible."
labels: ["Bug", "Mod Label Missing"]
assignees:
  - ricksouth
body:
  - type: markdown
    attributes:
      value: "Hi! This issue tracker page is for all of Serilum's mods combined.\nPlease specify which mod you are having trouble with or have a question about.\n\n> **Tell me the mod name! :)**"
  - type: input
    id: mod-name
    attributes:
      label: "Mod name:"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: "Mod version:"
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: "Minecraft version:"
    validations:
      required: true
  - type: dropdown
    id: modloader
    attributes:
      label: "Modloader:"
      options:
        - Fabric
        - Forge
        - NeoForge

        - Other / All
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: "Modloader version:"
  - type: dropdown
    id: environment
    attributes:
      label: "Environment:"
      options:
        - Singleplayer
        - Multiplayer
        - Both
    validations:
      required: true
  - type: textarea
    id: crash-report
    attributes:
      label: "Crash Report / Latest Log:"
      description: "If available. Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring."
  - type: textarea
    id: description
    attributes:
      label: "Description:"
    validations:
      required: true
