name: "💡 Submit a feature idea for an existing mod."
description: "Something could be improved or added! Please mention the mod name your feature request is for."
labels: ["Feature Request", "Mod Label Missing"]
assignees:
  - ricksouth
body:
  - type: markdown
    attributes:
      value: "Hi! This issue tracker page is for all of Serilum's mods combined.\nPlease specify which mod you are having trouble with or have a question about.\n\n> **Tell me the mod name! :)**"
  - type: input
    id: mod-name
    attributes:
      label: "Mod name:"
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: "Minecraft version:"
  - type: dropdown
    id: modloader
    attributes:
      label: "Modloader:"
      options:
        - Fabric
        - Forge
        - NeoForge

        - Other / All
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature description:"
    validations:
      required: true
