name: "Submit a feature idea for a new mod."
description: "Something that you'd think is a great addition to the game."
labels: ["Feature Request"]
assignees:
  - ricksouth
body:
  - type: markdown
    attributes:
      value: "Hi! This issue tracker page is for all of Serilum's mods combined.\nPlease specify which mod you are having trouble with or a question about.\n\n> **Tell me the mod name! :)**"
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      options:
        - Fabric
        - Forge
        - NeoForge

        - Other / All
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
    validations:
      required: true
