name: "❓ Submit a question."
description: "There are no wrong questions! If your question is about a specific mod, please mention the mod name."
labels: ["Question", "Mod Label Missing"]
assignees:
  - ricksouth
body:
  - type: markdown
    attributes:
      value: "Hi! This issue tracker page is for all of Serilum's mods combined.\nPlease specify which mod you are having trouble with or have a question about.\n\n> **Tell me the mod name! :)**"
  - type: input
    id: mod-name
    attributes:
      label: "Mod name:"
  - type: input
    id: mod-version
    attributes:
      label: "Mod version:"
  - type: input
    id: minecraft-version
    attributes:
      label: "Minecraft version:"
  - type: dropdown
    id: modloader
    attributes:
      label: "Modloader:"
      options:
        - Fabric
        - Forge
        - NeoForge
        - Other / All
  - type: input
    id: modloader-version
    attributes:
      label: "Modloader version:"
  - type: dropdown
    id: environment
    attributes:
      label: "Environment:"
      options:
        - Singleplayer
        - Multiplayer
        - Both
  - type: textarea
    id: question
    attributes:
      label: "Question:"
    validations:
      required: true
