name: "Submit a question."
description: "There are no wrong questions! If your question is about a specific mod, please mention the mod name."
labels: ["Mod Label Missing", "Question"]
assignees:
  - ricksouth
body:
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      options:
        - Fabric
        - Forge
        - NeoForge
        - Other / All
  - type: input
    id: modloader-version
    attributes:
      label: Modloader version
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Singleplayer
        - Multiplayer
        - Both
  - type: input
    id: mod-name
    attributes:
      label: Mod name
  - type: input
    id: mod-version
    attributes:
      label: Mod version
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
