name: "💬 Submit a comment. What's on your mind?"
description: "This can be about anything. Hello! :)"
labels: ["Comment", "Mod Label Missing"]
assignees:
  - ricksouth
body:
  - type: markdown
    attributes:
      value: "Hi! This issue tracker page is for all of Serilum's mods combined.\nPlease specify which mod you are having trouble with or have a question about.\n\n> **Tell me the mod name! :)**"
  - type: input
    id: mod-name
    attributes:
      label: "Mod name:"
  - type: input
    id: mod-version
    attributes:
      label: "Mod version:"
  - type: textarea
    id: comment
    attributes:
      label: "Comment:"
    validations:
      required: true
