name: "Submit something different. What you need is not covered by any of the previous options."
description: "I'd love to help. What's up?"
labels: []
assignees:
  - ricksouth
body:
  - type: textarea
    id: content
    attributes:
      label: What's on your mind?
    validations:
      required: true
